[package]
name = "aw_vr"
version = "0.1.0"
authors = ["Sgeo <sgeoster@gmail.com>"]

[dependencies]
libloading = "0.5"
lazy_static = "1.0.0"
ovr-sys = { version = "0.3.0", features = ["opengl"] }
nalgebra = "0.15.3"

[dependencies.easyhook]
path = "../easyhook"

[lib]
crate-type=["cdylib"]